apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-frontend-config
  labels:
    app: canopy-frontend
data:
  # Application configuration
  NEXT_PUBLIC_APP_NAME: "Canopy Superapp"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
