apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-frontend
spec:
  template:
    spec:
      containers:
      - name: canopy-frontend
        # Production-like resources for staging
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        # Staging environment variables
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
