apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canopy-local

bases:
  - ../../base

namePrefix: local-

commonLabels:
  environment: local

# Reduce replicas for local development
replicas:
  - name: canopy-frontend
    count: 1

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: canopy-frontend-config
    behavior: merge
    literals:
      - ENVIRONMENT=local
      - LOG_LEVEL=debug
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
